const express = require("express");
const fs = require("fs");
const path = require("path");

let router = express.Router();

router.use(express.static(__dirname + "/public"));

router.get("/", (req, res) => {
  res.render(__dirname + "/views/index.ejs", {
    pages: fs.readdirSync(__dirname + "/views/pages"),
    landingPage: "landing",
  });
});

var executablesOutput;
router.get("/executables.js", (req, res) => {
  if (executablesOutput) {
    res.send(executablesOutput);
  } else {
    let output = `/* autogenerated executables */\nvar executables = {}\n`;
    for (let executableFile of fs.readdirSync(__dirname + "/executables")) {
      output += `\n\n//${executableFile}\n`;
      output += fs.readFileSync(__dirname + "/executables/" + executableFile).toString();
    }
    executablesOutput = output;
    res.send(output);
  }
});

router.use("/auth", require("./routes/auth.js"));

module.exports = router;
